#!/bin/sh
#
# Visord    /etc/init.d initscript para Visord
#

### BEGIN INIT INFO
# Provides:          Visord
# Required-Start:    $network $local_fs $remote_fs
# Required-Stop:     $network $local_fs $remote_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: inicia y detiene Visord
# Description:       Creación de un demonio
### END INIT INFO

# Salir inmediatamente si un comando falla
# http://www.gnu.org/software/bash/manual/bashref.html#The-Set-Builtin
set -e

# Importar funciones LSB:
# start_daemon, killproc, status_of_proc, log_*, etc.
. /lib/lsb/init-functions

NAME=Visord
PIDFILE=/var/run/$NAME.pid
DAEMON=/usr/sbin/$NAME
DAEMON_OPTS="--daemon"

# Si el demonio no existe, salir.
test -x $DAEMON || exit 5

start()
{
    log_daemon_msg "Iniciando proceso  $NAME "
    start_daemon -p $PIDFILE -- $DAEMON $DAEMON_OPTS
    log_end_msg $?
}

stop()
{
    log_daemon_msg "Parando proceo $NAME "
    killproc -p $PIDFILE
    log_end_msg $?
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    status)
        if [ -e $PIDFILE ]; then
            status_of_proc -p $PIDFILE $DAEMON "$NAME proceso"
        else
            log_failure_msg "El proceso $NAME no esta corriendo "
            log_end_msg 0
        fi
        ;;
    restart)
        stop
        start
        ;;
    reload|force-reload)
        if [ -e $PIDFILE ]; then
            killproc -p $PIDFILE -SIGHUP
            log_success_msg "El proceso $NAME se ha cerrado satisfatoriamente "
        else
            log_failure_msg "El proceso $NAME  no esta corriendo"
            log_end_msg 0
        fi
        ;;
    *)
        echo "Uso:  $0 {start|stop|status|reload|force-reload|restart}"
        exit 2
        ;;
esac
